#ifndef _SAPPHIRE_THREAD_DEFINES_NONE_
#define _SAPPHIRE_THREAD_DEFINES_NONE_

//不使用线程


#define SAPPHIRE_AUTO_MUTEX
#define SAPPHIRE_LOCK_AUTO_MUTEX
#define SAPPHIRE_MUTEX(name)
#define SAPPHIRE_STATIC_MUTEX(name)
#define SAPPHIRE_STATIC_MUTEX_INSTANCE(name)
#define SAPPHIRE_LOCK_MUTEX(name)
#define SAPPHIRE_LOCK_MUTEX_NAMED(mutexName, lockName)
#define SAPPHIRE_AUTO_SHARED_MUTEX
#define SAPPHIRE_LOCK_AUTO_SHARED_MUTEX
#define SAPPHIRE_NEW_AUTO_SHARED_MUTEX
#define SAPPHIRE_DELETE_AUTO_SHARED_MUTEX
#define SAPPHIRE_COPY_AUTO_SHARED_MUTEX(from)
#define SAPPHIRE_SET_AUTO_SHARED_MUTEX_NULL
#define SAPPHIRE_MUTEX_CONDITIONAL(name) if(true)
#define SAPPHIRE_RW_MUTEX(name)
#define SAPPHIRE_LOCK_RW_MUTEX_READ(name)
#define SAPPHIRE_LOCK_RW_MUTEX_WRITE(name)
#define SAPPHIRE_THREAD_SYNCHRONISER(sync) 
#define SAPPHIRE_THREAD_WAIT(sync, lock) 
#define SAPPHIRE_THREAD_NOTIFY_ONE(sync) 
#define SAPPHIRE_THREAD_NOTIFY_ALL(sync) 
#define SAPPHIRE_THREAD_POINTER(T, var) T* var
#define SAPPHIRE_THREAD_POINTER_INIT(var) var(0)
#define SAPPHIRE_THREAD_POINTER_VAR(T, var) T* var = 0
#define SAPPHIRE_THREAD_POINTER_SET(var, expr) var = expr
#define SAPPHIRE_THREAD_POINTER_GET(var) var
#define SAPPHIRE_THREAD_POINTER_DELETE(var) { SAPPHIRE_DELETE var; var = 0; }
#define SAPPHIRE_THREAD_SLEEP(ms)
#define SAPPHIRE_THREAD_WORKER_INHERIT



#endif